### ISSUE TITLE
Color of start node doesn't get updated on completion of DFS visualization

### ISSUE THREAD

**Issue by rahulpathak-github** [Synergise-IIT-Bhubaneswar/algo-visualizer#22]
**Describe the bug**
On completion of visualization of the Depth-First-Search algorithm in a graph, color of all nodes gets updated to green except for the start node, which is still red.

**To Reproduce**
1. Create a minimum of two nodes by clicking on "Add a New Node" button
2. Create edges between the nodes (the start node should have an outdegree of at least one)
3. Select appropriate start node by clicking on the "Select Start Node" menu 
4. Select DFS algorithm by clicking on the "Select Algorithm" menu
5. Click on visualize, and wait for the visualization to be completed
6. After the visualization completes, notice the color of start node

**Expected behavior**
The color of start node should turn to green after completion of visualization

**Screenshots**
![image](https://user-images.githubusercontent.com/62535734/137150321-8105cb28-3f78-4d83-8d86-df4b3108090f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by vishnu921** [comment]
I would like to work on this issue.

**Comment by rahulpathak-github** [comment]
> I would like to work on this issue.

Yea sure, go ahead.
